### ISSUE TITLE
sbt.librarymanagement.ResolveException: Error downloading org.postgresql:postgresql:42.3.4

### ISSUE THREAD

**Issue by kingstar1115** [rockthejvm/slick-demo#3]
### [error] sbt.librarymanagement.ResolveException: Error downloading org.postgresql:postgresql:42.3.4
```

[error] sbt.librarymanagement.ResolveException: Error downloading org.postgresql:postgresql:42.3.4
[error]   Not found
[error]   Not found
[error]   download error: Caught java.io.IOException (Server returned HTTP response code: 502 for URL: https://repo1.maven.org/maven2/org/postgresql/postgresql/42.3.4/postgresql-42.3.4.pom) while downloading https://repo1.maven.org/maven2/org/postgresql/postgresql/42.3.4/postgresql-42.3.4.pom
[error]   not found: /home/golden/.ivy2/localorg.postgresql/postgresql/42.3.4/ivys/ivy.xml
[error]   not found: https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/org.postgresql/postgresql/42.3.4/ivys/ivy.xml
[error]   not found: https://repo.typesafe.com/typesafe/ivy-releases/org.postgresql/postgresql/42.3.4/ivys/ivy.xml
[error]         at lmcoursier.CoursierDependencyResolution.unresolvedWarningOrThrow(CoursierDependencyResolution.scala:345)
[error]         at lmcoursier.CoursierDependencyResolution.$anonfun$update$38(CoursierDependencyResolution.scala:314)
[error]         at scala.util.Either$LeftProjection.map(Either.scala:573)
[error]         at lmcoursier.CoursierDependencyResolution.update(CoursierDependencyResolution.scala:314)
[error]         at sbt.librarymanagement.DependencyResolution.update(DependencyResolution.scala:60)
[error]         at sbt.internal.LibraryManagement$.resolve$1(LibraryManagement.scala:59)
[error]         at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$12(LibraryManagement.scala:133)
[error]         at sbt.util.Tracked$.$anonfun$lastOutput$1(Tracked.scala:73)
[error]         at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$20(LibraryManagement.scala:146)
[error]         at scala.util.control.Exception$Catch.apply(Exception.scala:228)
[error]         at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$11(LibraryManagement.scala:146)
[error]         at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$11$adapted(LibraryManagement.scala:127)
[error]         at sbt.util.Tracked$.$anonfun$inputChangedW$1(Tracked.scala:219)
[error]         at sbt.internal.LibraryManagement$.cachedUpdate(LibraryManagement.scala:160)
[error]         at sbt.Classpaths$.$anonfun$updateTask0$1(Defaults.scala:3690)
[error]         at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error]         at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[error]         at sbt.std.Transform$$anon$4.work(Transform.scala:68)
[error]         at sbt.Execute.$anonfun$submit$2(Execute.scala:282)
[error]         at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:23)
[error]         at sbt.Execute.work(Execute.scala:291)
[error]         at sbt.Execute.$anonfun$submit$1(Execute.scala:282)
[error]         at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:265)
[error]         at sbt.CompletionService$$anon$2.call(CompletionService.scala:64)
[error]         at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error]         at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[error]         at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error]         at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[error]         at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[error]         at java.base/java.lang.Thread.run(Thread.java:829)
[error] (update) sbt.librarymanagement.ResolveException: Error downloading org.postgresql:postgresql:42.3.4
[error]   Not found
[error]   Not found
[error]   download error: Caught java.io.IOException (Server returned HTTP response code: 502 for URL: https://repo1.maven.org/maven2/org/postgresql/postgresql/42.3.4/postgresql-42.3.4.pom) while downloading https://repo1.maven.org/maven2/org/postgresql/postgresql/42.3.4/postgresql-42.3.4.pom
[error]   not found: /home/golden/.ivy2/localorg.postgresql/postgresql/42.3.4/ivys/ivy.xml
[error]   not found: https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/org.postgresql/postgresql/42.3.4/ivys/ivy.xml
[error]   not found: https://repo.typesafe.com/typesafe/ivy-releases/org.postgresql/postgresql/42.3.4/ivys/ivy.xml
```

How can I fix it?

**Comment by daniel-ciocirlan** [comment]
This library is a Java library, it should be searched on the general Maven repos. Set SBT to look at mvnrepository.com or look here: https://mvnrepository.com/artifact/org.postgresql/postgresql/42.6.0
